name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    name: Docker Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag v0es/discord-swamp-bot:$(date +%s)
    
   
  push:
    name: Push Docker Image to DockerHub
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Docker Login
    run: |
      docker login -u {{ secrets.DOCKER_USERNAME }} -p {{ secrets.DOCKER_PASSWORD }}

    - name: Docker Push
    run: docker push {{ secrets.DOCKER_USERNAME }}/discord-swamp-bot
