name: Code test
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pytest:
    runs-on: ubuntu-latest
    env: 
      YANDEX_API_KEY: ${{ secrets.YANDEX_API_KEY }}
      PYOWM_API_KEY: ${{ secrets.PYOWM_API_KEY }}
      PORTAINER_API_TOKEN: ${{ secrets.PORTAINER_API_TOKEN }}
      NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
      GUILD_ID: ${{ secrets.GUILD_ID }}
      DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
    strategy:
      matrix:
        python-version: [ '3.9', '3.x' ]
    steps:
      - uses: actions/checkout@v2
      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test code
        run: python -m unittest -v
        